### ISSUE TITLE
Authorisation example

### ISSUE THREAD

**Issue by olzorenko** [jselbie/stunserver#28]
Hi!

Could you please provide some how-to about enabling simple user/password authorisation for stunserver?
I'm not a C-programmer so it's really hard for me to figure this out.

It would be great if you add this to README/Wiki as well.

Looking forward to hear from you!

Kind Regards.

**Comment by jselbie** [comment]
Password and credential support, including long and short-term credentials
were enabled at the library level, but not on the server application
itself.  The reason it was not completed was because there were no known
STUN clients or client apps that supported STUN credentials. And so it was
not obvious how server support for credentials should work.  Single global
password passed at the command line?  A set of name/relam and passwords
read from a file or database?  Public/private key support for supporting
credentials that originated elsewhere?  The possibilities were endless, so
it was left unfinished with a lot of comments in the code giving
suggestions on how someone could hook it up.  And then the computing cost
of supporting authentication was more than the cost of simply allowing the
server to respond to all binding requests.

What is your scenario and how would like to see it supported?

jrs

**Comment by jselbie** [comment]
Hi, I never heard back, so I'm closing this out. Let me know if you want to discuss STUN auth scenarios in the future.
